#!/bin/bash
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

case ${MakeClean} in
	[Yy][Ee][Ss])
		make clean
		;;
esac

echo "Building liblog with flags ${MAKE_FLAGS}"
aclocal
automake --add-missing
autoconf
env CC="${CC}" CXX="${CXX}" LD="${LD}" AR=${AR} STRIP=${STRIP} RANLIB=${RANLIB} NM=${NM} \
CFLAGS="${CFLAGS} -Os" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}" \
./configure ${ConfigOpt} --prefix=/usr/local

make ${MAKE_FLAGS}
make install
